export const themeBg = '#e5e5e5'
export const themeText = '#000'
export const primaryBg = '#0369a1'
export const primaryText = '#fff'
export const secondaryBg = '#8c919b'
export const secondaryText = '#fff'